### PR TITLE
Demonstration gif replacement,

### PR DESCRIPTION
**Pull request by RushanKhan1**
Replaced the original pixelated gif demonstrating the cli with a new gif that is clearer and easier to read.

### CODE REVIEW

**Comment by ankushbhardwxj** [comment]
@RushanKhan1 - Post the GIF here in the comments please

**Comment by RushanKhan1** [comment]
@ankingcodes Sure, here you go:

code2

**Comment by ankushbhardwxj** [comment]
@RushanKhan1 - Check the syntax errors all over the place. They shouldn't be there, there's something wrong with your python distribution,

**Comment by RushanKhan1** [comment]
@ankingcodes  Thanks for pointing that out! I looked into it and found out that the warning that showed up in the gif is a recent addition in python version 3.8, as can be seen in the [release notes](https://docs.python.org/3.8/whatsnew/3.8.html#changes-in-python-behavior). Their compiler now checks if `is` and `is not` are used with certain types of literals, if found then the compiler raises a `SyntaxWarning`. They mention that it is better to use equality tests(`!=` and `==`) over identity checks(`is`, `is not`) when comparing with literals. The primary problem is that the [clint](https://pypi.org/project/clint/) module that you are using used an identity check with a string literal in one of their files([prompt.py](https://github.com/kennethreitz-archive/clint/blob/master/clint/textui/prompt.py#L69)) which is the cause of the problem. I fixed that locally and that solved the problem so I thought of fixing that in the source but it seems that the project has been abandoned because the last commit was made 3 years ago. I will be updating the gif, however I suggest you go with an alternative of clint, that is more up-to date, something like: [click](https://github.com/pallets/click) or [Python Fire](https://github.com/google/python-fire) since people using newer versions of python will face this problem too.

**Comment by RushanKhan1** [comment]
Here is the new gif:

code3

**Comment by ankushbhardwxj** [comment]
@RushanKhan1 - LGTM ! Thanks !

**Pull request merged**
