### PR TITLE
Migrate from os.system to subprocess.Popen

### LINKED ISSUE #33: Migration to "subprocess" for executing commands
The usage of `os.system` for calling the compilation and execution commands poses several issues we need to address, such as:
- It executes the passed command in a subshell without any control over the process. It would require ` < input.txt` to be suffixed to the command string to send the input data to the compiled executable.
- As previously discussed in #21, it is error-prone in non-GNU systems, and also leads to errors with file/directory names with special characters and whitespace.
- All we have access to is the return value once the process has finished executing. We can't examine or control the flow of data in `stdin` and `stdout`. It would also help if we want to automate the verification of right output to the given input.

The compilation command-executing strategy should therefore be migrated to `subprocess`, which is supported by the following points:
- We control the flow of data into `stdin` and out of `stdout` i. e. We read the data from `input.txt`, pass it into the subprocess call, obtain the data sent to `stdout` and format and display it as desired. It enables us to choose i. e. Define custom `stdin` and `stdout` for the subprocess call.
- Instead of executing the command in a subshell, a child process is created and executed, which is a safer and more efficient choice.
- Unlike `os.system`, we have access to a lot more than just the return value. We receive an object for the subprocess, whereafter we can choose to wait for it to finish or continue. We can communicate with the subprocess during its lifetime.
- We wouldn't need to worry about issues with quoting parameters that would contain special characters and/or whitespace, because a call made using `subprocess` would require the parameters to be provided in a list.
- It would be convenient to handle the absence of `gcc`/`g++` in PATH as well as improve the handling of #25.

I would like to work on the issue, if approved.

### PR DESCRIPTION
**Pull request by paramsiddharth**
Closes #33: **Migration to "subprocess" for executing commands**

Improvements:
- Uses `subprocess.Popen` instead of `os.system` for compilation and execution statements.
- In each of the child processes created, the flow of `stdin` and `stdout` are controlled i. e. Both are set in `subprocess.PIPE` and manually controlled using `obj.stdin` and `obj.communicate()`.
- Converted all file paths into OS-agnostic paths using `os.path.join`. The use of '/' as a separator might cause unexpected issues in several systems; `os.path` takes care of that.

The problem mentioned in #31 caused by whitespaces in the directory/file names is no longer a problem after the use of `subprocess`. The arguments are passed as an array to `subprocess.Popen`, which takes care of escaping the characters in an OS-agnostic way to avoid any possible error:
``` py]
...
obj = subprocess.Popen(['g++', full_filename, '-o', full_output_filename], 
                stdin=subprocess.PIPE, stdout=subprocess.PIPE)
...
```

The changes have been tested and Codemon successfully works in both GNU/UNIX-like (MSYS2, `bash`, WSL2, `xterm`) Windows (`cmd.exe`, PowerShell) environments.

### CODE REVIEW

**Comment by ankushbhardwxj** [comment]
@paramsiddharth - Could you reduce tabSize to 2 for all the files & use spaces instead of tabs ?

**Comment by paramsiddharth** [comment]
> @paramsiddharth - Could you reduce tabSize to 2 for all the files & use spaces instead of tabs ?

Sure! Let me do it.

**Comment by paramsiddharth** [comment]
Done.

**Comment by paramsiddharth** [comment]
PR #39 has introduced conflicts to `CodemonMeta.py`. Let me resolve them.

**Comment by paramsiddharth** [comment]
I have resolved the conflicts. Please have a look.

**Comment by paramsiddharth** [comment]
Turns out there are still conflicts and information lost.

**Pull request closed without merging**
