### PR TITLE
Code Refactoring

### PR DESCRIPTION
**Pull request by ag-hcoder**

### CODE REVIEW

**Comment by ankushbhardwxj** [comment]
@ag-hcoder : This PR is too small to be given points for. Check the code for more refactoring, I'm sure the code can be made a lot more tight !

**Comment by ag-hcoder** [comment]
Yeah sure. Are there any fixed standards that I should be following?

**Comment by ankushbhardwxj** [comment]
@ag-hcoder - As for standard, I'd suggest keep code readable, concise and better than before. You may make your commits, I'll request changes as necessary during code review.

**Comment by ag-hcoder** [comment]
Just one suggestion, should we go for the code being PEP-8 compliant?

**Comment by ankushbhardwxj** [comment]
Sure !

**Comment by ankushbhardwxj** [comment]
@ag-hcoder : Are you making changes in this PR or should we close it ?

**Comment by ag-hcoder** [comment]
I'm currently busy with some university work. I will get back to work once that is done. I hope it is fine with you

**Pull request closed without merging**
