### PR TITLE
setup for codemon [java]

### PR DESCRIPTION
**Pull request by alphaX86**
### Description:
- This PR solves #14 and codes are now refactored (ref #30) 
- Templates for Java are added
- **Before running, you may need to run `pip install .` again to see the upcoming changes**
- All functions are now refactored and remained untouched
- NO EXTRA CHANGES ARE ADDED THIS TIME

### CODE REVIEW

**Comment by alphaX86** [comment]
@ankingcodes I refined this again from scratch (re-forked the repo) and tried to keep simple. Review again and let me know IFF I need to change again.

**Comment by alphaX86** [comment]
I hope this will be reviewed ASAP I guess. Please finish review to avoid stale changes as did before. Thanks 😄

**Comment by alphaX86** [comment]
@ankingcodes requesting you to review and notify me to avoid further stale issues

**Comment by alphaX86** [comment]
Let me know what changes are to be added before merging other PRs to avoid conflicts. Thanks!

**Comment by ankushbhardwxj** [comment]
@alphaX86 - You might notice PR #55 has a really elegant code to support creation of 3 types of files - CPP, Java, Python along with web scraping support from the Codeforces website. That presents a better solution to the overall functionality of codemon. Hence, I'm looking forward to get that merged. 

I don't know yet if @Enigmage would handle the templates part of the issue, if he does, then unfortunately I'll have to close this PR. If he doesn't, you'll have to make changes to your PR such that the templates part is done by you and then this PR may be merged.

**Comment by alphaX86** [comment]
Hmm, okay then

**Comment by ankushbhardwxj** [comment]
@alphaX86 - closing this PR since #55 has been merged and provides a better way to solve the issue. Will give some points for making the PR.

**Pull request closed without merging**
