### PR TITLE
Fixed the issue of compilation in case of windows OS

### PR DESCRIPTION
**Pull request by lucifer0987**
Things changed :

- Earlier, the fix which was merged wasn't able to account for whitespaces and created an error when the directory contained a whitespace.
More info about the issue here : https://github.com/ankingcodes/codemon/issues/21#issuecomment-736617735

### CODE REVIEW

**Comment by ankushbhardwxj** [comment]
@paramsiddharth - Does the issue you created at #33 fix this ?

**Comment by lucifer0987** [comment]
@ankingcodes Till @paramsiddharth fixes this issue, I won't be able to work on any other issue. Because currently, the programs don't compile on my system because of whitespace error. So, if it would be easier for me if @paramsiddharth fixes #33 asap or you merge this PR. 
Whatever works for you.

**Comment by ankushbhardwxj** [comment]
@lucifer0987 - Check #33, Param has presented a nice alternative to your PR. 

> I won't be able to work on any other issue.

Try using WSL or a UNIX terminal, its working fine there.

**Comment by paramsiddharth** [comment]
> @paramsiddharth - Does the issue you created at #33 fix this ?

Yes, it certainly does. That is one of the most important reasons to use `subprocess` instead of `os.system`.

**Comment by lucifer0987** [comment]
@ankingcodes yeah, that's the issue. I don't have UNIX or WSL terminal. I will wait for @paramsiddharth then.

**Pull request closed without merging**
